"""Add deleted column to captures table

Revision ID: b1b22439980d
Revises: 
Create Date: 2025-10-28 00:56:26.999952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b22439980d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captures', sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.create_index(op.f('ix_captures_deleted'), 'captures', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_captures_deleted'), table_name='captures')
    op.drop_column('captures', 'deleted')
    # ### end Alembic commands ###
